reddit/reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :subs

  resources :posts do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]

end

reddit/reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit/reddit/app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :author,
  foreign_key: :user_id,
  class_name: :User 
  
  belongs_to :post

  has_many :child_comments,
  foreign_key: :parent_comment_id,
  class_name: :Comment

  belongs_to :parent_comment, 
  foreign_key: :parent_comment_id,
  class_name: :Comment,
  optional: true
end

reddit/reddit/app/models/post.rb
class Post < ApplicationRecord

  belongs_to :author,
  foreign_key: :user_id,
  class_name: :User

  # belongs_to :sub,
  # foreign_key: :sub_id,
  # class_name: :Sub

  has_many :postsubs
  # foreign_key: :post_id,
  # class_name: :Postsub,
  # inverse_of: :post

  has_many :subs,
  through: :postsubs

  has_many :comments

  
  
end

reddit/reddit/app/models/postsub.rb
class Postsub < ApplicationRecord

  # validates :post_id, :sub_id, presence: true

  belongs_to :sub

  belongs_to :post




end

reddit/reddit/app/models/sub.rb
class Sub < ApplicationRecord

  belongs_to :moderator,
  foreign_key: :user_id,
  class_name: :User 

  has_many :postsubs
  # foreign_key: :sub_id,
  # class_name: :Postsub,
  # inverse_of: :sub

  has_many :posts,
  through: :postsubs

end

reddit/reddit/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password
  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user&.is_password?(password) ? user : nil
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  has_many :posts
  has_many :subs
  has_many :comments

end

reddit/reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def require_login
    redirect_to new_session_url unless current_user
  end

end

reddit/reddit/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :require_login

  def new; end
  
  
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

end

reddit/reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_login

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    # debugger

    # @post.sub_ids = params[:sub_ids]
    # params[:subs_id].each do |sub_id|
    #   Postsub.create(post_id: @post.id, sub_id: sub_id)
    # end
    if @post.save
      redirect_to subs_url #post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    redirect_to subs_url unless current_user == @post.author
  end

  def update
    @post = Post.find_by(id: params[:id])
  

    if @post&.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to user_url(current_user)
  end

  def show
    @post = Post.find_by(id: params[:id])
  end


  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

end

reddit/reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
 
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = "Invalid credentials"
      render :new
    end 

  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

reddit/reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  

  before_action :require_login

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by(id: params[:id])
  end

  def edit
    @sub = current_user.subs.find_by(id: params[:id])
  end

  def update
    @sub = current_user.subs.find_by(id: params[:id])
    if @sub&.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    @sub.destroy
    redirect_to subs_url
    flash[:errors] = @sub.errors.full_messages
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
  
end

reddit/reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end



private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit/reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit/reddit/app/helpers/comments_helper.rb
module CommentsHelper
end

reddit/reddit/app/helpers/posts_helper.rb
module PostsHelper
end

reddit/reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit/reddit/app/helpers/subs_helper.rb
module SubsHelper
end

reddit/reddit/app/helpers/users_helper.rb
module UsersHelper
end

reddit/reddit/app/views/comments/new.html.erb
<h2> New Comment </h2>

<form action=<%= comments_url %> method="POST">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
  <input type="hidden" name="comment[post_id]" value=<%= params[:post_id]%>>
  <label>
    Comment <input type="textarea" name="comment[content]">
  </label>

  <input type="submit" value="Add Comment">
</form>

reddit/reddit/app/views/comments/show.html.erb
<h5> Show Comment </h5>
<% top_comment = Comment.find_by(id: params[:id]) %>
  <%= top_comment.content %>
  <%= top_comment.author.username %>
<% top_comment.child_comments.each do |comment| %>
  <%= comment.content %>
  <%= comment.author.username %>
  <a href=<%= comment_url(comment)%>>Children</a>
  <br>
<% end %>

reddit/reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <% if current_user %>
    <form action=<%= session_url %> method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Sign Out">
    </form>
  <% end %>

  <%= flash[:errors] %>
  <% if current_user %>
    <%= current_user.username %>
  <% end %> 
  <body>
    <%= yield %>
  </body>
</html>

reddit/reddit/app/views/posts/edit.html.erb
<h3> Edit Post </h3>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token%>>
  <input type="hidden" name="_method" value="PATCH">
  
  <label for="">
    title <input type="text" name="post[title]" value=<%= @post.title %>>
  </label>

  <label for="">
    url <input type="text" name="post[url]" value=<%= @post.url %>>
  </label>
  
  <label for="">
    content <input type="text" name="post[content]" value=<%= @post.content %>>
  </label>

  <br>
  <label for=""> Subs </label>

    <input type="hidden" name="post[sub_ids][]" value="">
  <% current_user.subs.each do |sub| %>
    <label><h6><%= sub.title %></h6>
      <input 
        type="checkbox" 
        name="post[sub_ids][]" 
        value="<%= sub.id %>"
        <%= "checked" if sub.posts.include?(@post) %> 
        >
    </label>
  <% end %>
  <hr>
  <input type="submit" value="Update Post">
</form >

reddit/reddit/app/views/posts/new.html.erb
<h3> New Post </h3>

<form action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token%>>
  <label for="">
    title <input type="text" name="post[title]">
  </label>

  <label for="">
    url <input type="text" name="post[url]">
  </label>
  
  <label for="">
    content <input type="text" name="post[content]">
  </label>

  <br>
  
  <label for=""> Subs: </label>

    <ul>
      <% current_user.subs.each do |sub| %>
        <li>
          <label>
            <%= sub.title %>
              <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>">
          </label>
        </li>
      <% end %>
    </ul>
  <input type="submit" value="Create Post">
</form >

reddit/reddit/app/views/posts/show.html.erb
 <h3> <%= @post.title %> </h3> 
  <%= @post.content %>
  <br>
  <a href="<%= @post.url %>"> URL </a>

<!-- Only the Parents are shown -->

<ul>
  <% @post.comments.where(parent_comment_id: nil).each do |comment| %>
    <br>
    <li>
      <%= comment.author.username %>
    </li>
    <li>
      <%= comment.content %>
    </li>
    <a href=<%= comment_url(comment)%>>Children</a>
  <% end %>
</ul>

<a href=<%= new_post_comment_url(@post) %>> Add Comment </a>
  





  

reddit/reddit/app/views/subs/index.html.erb
Subs Index

reddit/reddit/app/views/subs/new.html.erb
<h3> New Sub </h3>


<form action=<%= subs_url %> method="POST">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
   
   <label for="">
    title <input type="text" name="sub[title]">
   </label>


   <label for="">
    description <input type="textarea" name="sub[description]">
   </label>

   <input type="submit" value="Create Sub">
</form>

reddit/reddit/app/views/subs/show.html.erb
<h3> Welcome to <%= @sub.title  %> </h3>

reddit/reddit/app/views/users/new.html.erb
<h3>Sign Up</h3>

<form action=<%= users_url %> method="Post">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token%>>
  <label for="">
    username <input type="text" name="user[username]">
  </label>
  <label for="">
    password <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Create User">
</form>